## GAN

https://machinelearningmastery.com/what-are-generative-adversarial-networks-gans/

https://machinelearningmastery.com/how-to-develop-a-conditional-generative-adversarial-network-from-scratch/

In [15]:
import numpy as np, pandas as pd
from utils import *

In [2]:
import yfinance as yf

In [12]:
import yfinance as yf

start = "2019-01-01"
end   = "2020-03-20"

stocks = ["MSFT"]

df = yf.download(stocks, 
                     #period = "1Y",
                      start= start, 
                      end= end, 
                      progress=False)


In [4]:
def ma5(s):
    print(type(s))
    df = pd.DataFrame(s)
    for i in range(1,5):
        df[str(i)] = s.shift(i)
    return pd.Series(df.values.mean(axis = 1), index=s.index, name = "ma5")
    #return pd.DataFrame(df.values.mean(axis = 1), index=s.index, columns = ["ma5"])
        

In [13]:
df["ma5"] = ma5(df["Close"]).fillna(method = "backfill")
df.drop(columns = ["Adj Close"], inplace = True)


<class 'pandas.core.series.Series'>


In [162]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'ma5'], dtype='object')

In [41]:
window = 2
rolls = rolling_window_bert_2nd_dim(df.values,window)
target = df.Close[window:]

In [42]:
target

Date
2019-01-03     97.400002
2019-01-04    101.930000
2019-01-07    102.059998
2019-01-08    102.800003
2019-01-09    104.269997
                 ...    
2020-03-13    158.830002
2020-03-16    135.419998
2020-03-17    146.570007
2020-03-18    140.399994
2020-03-19    142.710007
Name: Close, Length: 305, dtype: float64

In [99]:
test = np.arange(100).reshape(20,5)
d = df.values[:20,0:-1]
d32 = np.float32(d)

In [100]:
print(test.shape)
print(d.shape)
print(d32.shape)

(20, 5)
(20, 5)
(20, 5)


In [103]:
test.dtype

dtype('int64')

In [150]:
print(test.strides)
print(d.strides)
print(d32.strides)

(40, 8)
(8, 2456)
(4, 80)


In [153]:
roll_test = rolling_window_bert_2nd_dim(test,2)
roll_d = rolling_window_bert_2nd_dim(d,2)
roll_d32 = rolling_window_bert_2nd_dim(d32,2)

In [144]:
test = np.array([5*[x] for x in np.arange(5)])

In [145]:
roll_test = rolling_window_bert_2nd_dim(test, 2)

In [155]:
roll_test


array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]]])

In [148]:
roll_test[0:2]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]]])

In [154]:
print(roll_test.strides)
print(roll_d.strides)
print(roll_d32.strides)

(40, 40, 8)
(8, 12280, 2456)
(4, 400, 80)


In [161]:
roll_d32.T.strides

(80, 400, 4)

In [160]:
roll_d32.strides

(4, 400, 80)

In [127]:
np.random.random((30,5)).strides

(40, 8)

In [128]:
np.random.random((30,2,5)).strides

(80, 40, 8)

In [152]:
def rolling_window_bert_2nd_dim(a, window):
    shape = (a.shape[0] - window + 1, window, a.shape[1])
    strides = (a.strides[0], a.strides[1]*a.shape[1], a.strides[1])
    #strides = (a.strides[0]*window, a.strides[0], a.strides[1])
    #print(shape, strides)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

In [85]:
test

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101],
       [102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119]])

In [82]:
2456/64

38.375

(8, 2456)

In [40]:
df

Open        High         Low       Close    Volume  \
Date                                                                   
2018-12-31  101.290001  102.400002  100.440002  101.570000  33173800   
2019-01-02   99.550003  101.750000   98.940002  101.120003  35329300   
2019-01-03  100.099998  100.190002   97.199997   97.400002  42579100   
2019-01-04   99.720001  102.510002   98.930000  101.930000  44060600   
2019-01-07  101.639999  103.269997  100.980003  102.059998  35656100   
...                ...         ...         ...         ...       ...   
2020-03-13  147.500000  161.910004  140.729996  158.830002  92727400   
2020-03-16  140.000000  149.350006  135.000000  135.419998  87905900   
2020-03-17  140.000000  147.500000  135.000000  146.570007  81059800   
2020-03-18  138.000000  146.000000  135.020004  140.399994  81593200   
2020-03-19  142.770004  150.149994  139.000000  142.710007  85922700   

                   ma5  
Date                    
2018-12-31  100.816000  
2019-01-02  100.816000  
2019-01-03  100.816000  
2019-01-04  100.816000  
2019-01-07  100.816000  
...                ...  
2020-03-13  152.612000  
2020-03-16  149.572000  
2020-03-17  146.702002  
2020-03-18  144.056000  
2020-03-19  144.786002  

[307 rows x 6 columns]

In [47]:
rolls[:,:,:]

array([[[ 1.01290001e+002,  1.02400002e+002,  1.00440002e+002,
          1.01570000e+002,  3.31738000e+007,  1.00816000e+002],
        [ 1.11269820e-308,  7.32088548e-312, -6.79864536e-167,
         -1.55221119e+033, -3.11108604e-153,  4.37835928e-007]],

       [[ 9.95500031e+001,  1.01750000e+002,  9.89400024e+001,
          1.01120003e+002,  3.53293000e+007,  1.00816000e+002],
        [ 9.73635329e-309,  7.21478569e-312, -3.14694826e+277,
         -7.39359174e+130,  3.32270549e+223, -6.44807025e+236]],

       [[ 1.00099998e+002,  1.00190002e+002,  9.71999969e+001,
          9.74000015e+001,  4.25791000e+007,  1.00816000e+002],
        [ 9.73639573e-309,  7.00258613e-313, -1.53459557e+173,
          1.89613372e+235,  8.87556794e+216,  1.97745564e-021]],

       ...,

       [[ 1.40000000e+002,  1.49350006e+002,  1.35000000e+002,
          1.35419998e+002,  8.79059000e+007,  1.49572000e+002],
        [ 4.62595083e-312,  1.97494113e-115, -3.82362268e+201,
         -8.77947124e-036, -2

In [39]:
windows.shape

(303, 5, 6)

In [36]:
target.shape

(302,)

In [22]:
df.values.shape

(307, 6)

In [24]:
import matplotlib.pyplot as plt

In [32]:
df.Close[:10].index.nunique()

10

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Dropout, Flatten

In [3]:
def define_discriminator(in_shape=(28,28,1)):
    model = Sequential()
    # downsample
    model.add(Conv2D(128, (3,3), strides=(2,2), padding='same', input_shape=in_shape))
    model.add(LeakyReLU(alpha=0.2))
    # downsample
    model.add(Conv2D(128, (3,3), strides=(2,2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    # classifier
    model.add(Flatten())
    model.add(Dropout(0.4))
    model.add(Dense(1, activation='sigmoid'))
    # compile model
    opt = Adam(lr=0.0002, beta_1=0.5)
    model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
    return model

In [ ]:
n_features = 5
    model = Sequential()
    model.add(LSTM(100, input_shape = (n_steps, n_features), return_sequences = True))
    model.add(TimeDistributed(Dense(20, activation='elu')))
    model.add(Flatten())
    model.add(Dense(1, activation='elu'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    print(model.summary())
    return model

In [ ]:
# define the standalone generator model
def define_generator(latent_dim):
    model = Sequential()
    model.add(LSTM(100, input_shape = (n_steps, n_features), return_sequences = True))
    model.add(LSTM(n_nodes, input_dim=latent_dim))
    model.add(LSTM(100, input_shape = (n_steps, n_features), return_sequences = True))
    model.add(TimeDistributed(Dense(20, activation='elu')))
    # upsample to 14x14
    model.add(Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    # upsample to 28x28
    model.add(Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    # generate
    model.add(Conv2D(1, (7,7), activation='tanh', padding='same'))
    return model

In [5]:
# define the standalone generator model
def define_generator(latent_dim):
    model = Sequential()
    # foundation for 7x7 image
    n_nodes = 128 * 7 * 7
    model.add(Dense(n_nodes, input_dim=latent_dim))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Reshape((7, 7, 128)))
    # upsample to 14x14
    model.add(Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    # upsample to 28x28
    model.add(Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
    model.add(LeakyReLU(alpha=0.2))
    # generate
    model.add(Conv2D(1, (7,7), activation='tanh', padding='same'))
    return model

In [ ]:
def define_gan(generator, discriminator):
    # make weights in the discriminator not trainable
    discriminator.trainable = False
    # connect them
    model = Sequential()
    # add generator
    model.add(generator)
    # add the discriminator
    model.add(discriminator)
    # compile model
    opt = Adam(lr=0.0002, beta_1=0.5)
    model.compile(loss='binary_crossentropy', optimizer=opt)
    return model